<a href="https://colab.research.google.com/github/Anoziqq/NN/blob/main/Lab2/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 1
#З дисципліни "Нейронні мережі"
##Виконав студент:
###групи АнД-31
###Лаврій Руслан

## Завдання
### 1. За матеріалами [2] ознайомитись із засадами бібліотеки TensorFlow:
### - засвоєння поняття тензору
### - знати різні способи створення тензорів
### - створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
### - продемонструвати основні математичні операції над тензорами
### - провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)
### 2. Відповіді оформити .ipynb документами за кожним з попередніх пунктів
### 3. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab2 де мають бути .ipynb файл та необхідні файли з даними


##Імпорт TensorFlow 

In [ ]:
import numpy as np
import pandas as pd 
import tensorflow as tf
print ( tf . __version__ )

2.8.2


##Створення за допомогою tf.constant()

In [ ]:
scalar = tf.constant(5)
print(scalar)
print(scalar.ndim)
vector = tf.constant([5, 10])
print(vector)
print(vector.ndim)
matrix = tf.constant([[10, 7],
                      [7, 10]])
print(matrix)
print(matrix.ndim)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(5, shape=(), dtype=int32)
0
tf.Tensor([ 5 10], shape=(2,), dtype=int32)
1
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
3


##Створення за допомогою tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


## Створення випадкових тензорів

In [59]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


##Тензори  одиниць і нулів

In [ ]:

print(tf.ones(shape=(3, 2)))
print(tf.zeros(shape=(3, 2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


##shape, rank, size, axis

In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32)
tensor = tf.constant(numpy_A, shape=[2, 4, 3])
print(tensor)
print("Rank:", tensor.ndim)
print("Shape:", tensor.shape)
print("Axis:", tensor.shape[0])
print("Size:", tf.size(tensor).numpy())

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)
Rank: 3
Shape: (2, 4, 3)
Axis: 2
Size: 24


##Математичні операції

In [ ]:
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor+10)
print(tensor*10)
print(tensor-10)
print(tensor/10)

print(tf.multiply(tensor, tensor))
print(tensor @ tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


## CRUD

In [ ]:
tensor = tf.Variable(np.arange(0, 5))
print(tensor)
tensor[4].assign(10)
tensor.assign_add([10,10,10,10,10])
print(tensor)

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>
<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 20])>


## reshape, інтеграцію з np.array, pd.DataFrame

In [58]:
tensor = tf.Variable(np.arange(0, 6))
print(tf.reshape(tensor, shape=(2,3)))
vector = np.array([1,2,3,4])
print(tf.constant(vector))
dataFrame1 = pd.DataFrame(vector)
print(tf.convert_to_tensor(dataFrame1))


tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int64)
